### ISSUE TITLE
Markdown question

### ISSUE THREAD

**Issue by alexlinz** [McMahonLab/geodes#5]
Why is R Markdown highlighting file names in red and how can I stop this?

**Comment by sstevens2** [comment]
Does it do it in Rstudio?  Might be a github+Rmd rendering oddity? It doesn't seem to be doing this in the html.

My only thoughts are that it looks like it is code blocks that are actually supposed to be bash but you've specified r instead.  I'm not sure it will fix it..but you should probably change

\```{r, eval = F}
to 
\```{bash, eval = F}

in any case since the code blocks are actually bash.  It *might* change the highlighting then and not have the files in red.

**Comment by alexlinz** [comment]
That worked, thanks!
