### ISSUE TITLE
Mapping .sam file merging

### ISSUE THREAD

**Issue by alexlinz** [McMahonLab/geodes#8]
I'm using several samtools functions to merge the sam files produced by the bwa mapping on each split fastq file. Is there a more elegant way to do this? Is samtools merge an appropriate tool to use?

**Comment by sstevens2** [comment]
I think samtools is a great way to merge the files.  [Link to where someone asked a similar question on biostars](https://www.biostars.org/p/9864/).

Sidenote: I would consider storing these as bam files, if you aren't already, unless you are parsing something out of the guts of the sam versions, since they are smaller that way.  Can always switch them back to sam with samtools.

**Comment by alexlinz** [comment]
Thanks for the feedback! I think samtools has undergone substantial changes in their last update, so there are two forms of documentation online and many questions on Stack Overflow are addressed in the old syntax, which is why I've been having so much trouble getting commands to work. But now that I'm getting the hang of samtools, it's easier to use.
